services:
  # PHP Application Service (Laravel)
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        user: ${USER_NAME:-pit}
        uid: ${USER_ID:-1000}
        group: ${USER_GROUP:-pit}
        gid: ${USER_GID:-1000}
    container_name: ${CONTAINER_NAME_APP:-ciberpit}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini # Optional
    networks:
      - network
    depends_on:
      - db_primary

  # Nginx Web Server Service
  web:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME_WEB:-ciberpit_web}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - app

  # Primary MySQL Database Service
  db_primary:
    image: mysql:8.0 # Or your required MySQL version
    container_name: ${CONTAINER_NAME_DB:-ciberpit_db}
    restart: unless-stopped
    ports:
      # Expose DB port to host for external access (e.g., DB GUI)
      - "${DB_PRIMARY_PORT_ON_HOST:-33060}:3306"
    environment:
      # These values are taken from your .env file (or use fallbacks)
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-pit}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PRIMARY_ROOT_PASSWORD:-secret_root}
    volumes:
      # Named volume for persistent storage of database data
      - db_data:/var/lib/mysql
    networks:
      - network

# Custom Bridge Network Definition
networks:
  network:
    driver: bridge

# Named Volumes Definition
volumes:
  # Volume for the primary database
  db_data:
    driver: local
